# Generated by Django 3.2.20 on 2023-09-18 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bvhffh',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jfjf', models.BigIntegerField()),
                ('yrur', models.BigIntegerField()),
            ],
        ),
    ]
